/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team.bitcode.stock_market;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 *
 * @author DUSH
 */
public class panelNewsForm extends javax.swing.JPanel {

    /**
     * Creates new form panelNewsForm
     */
    int x=1;
    int y=2;
    public static JPanel scroll;
    
    public panelNewsForm() {
        initComponents();
        scroll=jPanel1;
        new Timer().schedule(new TimerTask() {
            @Override
            public void run() {
                openDialog();
                showNews();
                closeDialog();
            }
        }, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jDialog1.setAlwaysOnTop(true);
        jDialog1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jPanel14.setBackground(new java.awt.Color(233, 233, 233));
        jPanel14.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/10.gif"))); // NOI18N
        jLabel7.setText("Processing");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setIconTextGap(10);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel14.add(jLabel7);
        jLabel7.setBounds(151, 34, 74, 58);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jdialog_back.jpg"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel14.add(jLabel2);
        jLabel2.setBounds(-12, -15, 390, 150);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialog1.getContentPane().add(jPanel13, java.awt.BorderLayout.CENTER);

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1);
        jPanel1.setBounds(73, 82, 1212, 500);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Top 10 Story of Finance");
        add(jLabel1);
        jLabel1.setBounds(73, 19, 211, 22);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void showNews(){
        try{
            if(InternetConnection.getInternetStatus()){
            Elements p_tags;
                do{
                    Document doc =  Jsoup.parse(readURL("https://finance.yahoo.com/"));
                    p_tags = doc.select("div#slingstoneStream-0-Stream").select("a");
                }while(p_tags.size()<=0);
                
                int i=0,j=10;       
                jPanel2.removeAll();
                    for (Element p : p_tags) {
                       if(i<j){
                            String link="https://finance.yahoo.com"+p.attr("href");;
                            String news=p.text();
                            if(news.equals("")){
                                j++;
                            }
                            else{
                                jPanel2.add(setTab(news, link));
                                y=y+85;
                            }
                            
                       }
                       else{
                           break;
                       }
                       i++;
                    }
                    jPanel2.setPreferredSize(new Dimension(1188, y+5));
                    jScrollPane1.repaint();
                    jPanel1.validate();
                    jPanel1.repaint();
            }
               }catch(Exception ex){
                   System.out.println(ex);
               }
               
    }
    
    public static String readURL(String url) {

        String fileContents = "";
        String currentLine = "";

        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(new URL(url).openStream()));
            fileContents = reader.readLine();
            while (currentLine != null) {
                currentLine = reader.readLine();
                fileContents += "\n" + currentLine;
            }
            reader.close();
            reader = null;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error Message", JOptionPane.OK_OPTION);
            e.printStackTrace();

        }

        return fileContents;
    }
    
    public JPanel setTab(String news, String link){
       
            JPanel p= new JPanel();
            p.setLayout(null);
            p.setSize(new Dimension(1190, 80));
            p.setBounds(x, y, jPanel1.getWidth(), 80);
            p.setBackground(Color.black);
            p.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 153)));
            p.setVisible(true);
            
            
            /*JLabel lblImage = new JLabel();
            lblImage.setBounds(0, 0, p.getWidth()-2, 80);
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/news_panel.png")));
            lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            */
            JLabel lblNews = new JLabel();
            lblNews.setFont(new java.awt.Font("Tahoma", 1, 14)); 
            lblNews.setForeground(new java.awt.Color(255, 255, 255));
            lblNews.setBounds((int)(p.getWidth()*0.00840336), 10, p.getWidth()-40, 30);
            lblNews.setText(news);
            
            JButton btnClick = new JButton();
            btnClick.setBackground(new java.awt.Color(0, 0, 0));
            btnClick.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            btnClick.setForeground(new java.awt.Color(255, 255, 255));
            btnClick.setText("See More >>");
            btnClick.setBounds((int)(p.getWidth()*0.88285294), 40, 110, 23);
            
            btnClick.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        Desktop desktop = java.awt.Desktop.getDesktop();
                        URI oURL = new URI(link);
                        desktop.browse(oURL);
                        FxMediaExample2.frame.setState(Frame.ICONIFIED);
                    } catch (URISyntaxException ex) {
                        JOptionPane.showMessageDialog(FxMediaExample2.frame, "Can't open browser", "Error", JOptionPane.WARNING_MESSAGE);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(FxMediaExample2.frame, "Can't connect to Internet", "No Internet Connection", JOptionPane.WARNING_MESSAGE);
                    }
                }
            });
           //lblImage.setVisible(true);
            lblNews.setVisible(true);
            btnClick.setVisible(true);
            
            p.add(btnClick);
            p.add(lblNews);
            //p.add(lblImage);
            
        return p;
        
    }
    
    private void openDialog(){
            jDialog1.setUndecorated(true);
            jDialog1.setSize(392, 151);
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            jDialog1.setLocation(dim.width/2-jDialog1.getSize().width/2, dim.height/2-jDialog1.getSize().height/2);
            jDialog1.setVisible(true);
            FxMediaExample2.frame.setEnabled(false);
            
    }
    
    private void closeDialog(){
            FxMediaExample2.frame.setEnabled(true);
            jDialog1.dispose();
    }
    
}
