/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team.bitcode.stock_market;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import yahoofinance.Stock;
import yahoofinance.YahooFinance;

/**
 *
 * @author DUSH
 */
public class panelPortfolios extends javax.swing.JPanel {

    public static String player="";
    int x=0;
    int y1=10,y2=10,y3=10;
    public static int show=0;
    public static JLabel remainingTurns;
    private double profitAndLost=0.00;
    public static JTabbedPane tabpane;
    public static JLabel lblacc;
    public static JLabel lblacc2;
    public static JLabel lblPF;
    public static JLabel lblPF2;
    public static JButton btnStats;
    
    public panelPortfolios() {
        initComponents();
        tabpane=jTabbedPane1;
        lblacc=lblAccBal1;
        lblacc2=lblAccBal;
        lblPF=lblPAndL1;
        btnStats=jButton1;
        remainingTurns=lblRemainingTurns;
        lblPlayerName.setText(player);
        lblRemainingTurns.setText("Remaning Turns: "+Frame.remainTurn);
        
        new Timer().schedule(new TimerTask() {
                        @Override
                        public void run() {
                            
                            openDialog();
                            getTransaction(panelPortfolios.player);
                            closeDialog();
                        }
                    }, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        lblAccBal = new javax.swing.JLabel();
        lblPAndL = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        lblRemainingTurns = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblPAndL1 = new javax.swing.JLabel();
        lblAccBal1 = new javax.swing.JLabel();

        jDialog1.setAlwaysOnTop(true);
        jDialog1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jPanel14.setBackground(new java.awt.Color(233, 233, 233));
        jPanel14.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/10.gif"))); // NOI18N
        jLabel7.setText("Processing");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setIconTextGap(10);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel14.add(jLabel7);
        jLabel7.setBounds(151, 34, 74, 58);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jdialog_back.jpg"))); // NOI18N
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel14.add(jLabel8);
        jLabel8.setBounds(-12, -15, 390, 150);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialog1.getContentPane().add(jPanel13, java.awt.BorderLayout.CENTER);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lblPlayerName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPlayerName.setText("Player Name");
        add(lblPlayerName);
        lblPlayerName.setBounds(42, 41, 1000, 29);

        lblAccBal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAccBal.setText("0.00");
        add(lblAccBal);
        lblAccBal.setBounds(170, 130, 190, 17);

        lblPAndL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPAndL.setText("0.00");
        add(lblPAndL);
        lblPAndL.setBounds(173, 176, 183, 17);

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1243, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("               Current Stocks             ", jPanel1);

        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1238, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel7);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("             BUY ORDERS             ", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1238, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(jPanel8);

        jPanel6.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("            SELL ORDERS           ", jPanel6);

        jPanel2.add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("               ORDER HISTOTRY               ", jPanel2);

        add(jTabbedPane1);
        jTabbedPane1.setBounds(42, 253, 1250, 372);

        lblRemainingTurns.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(lblRemainingTurns);
        lblRemainingTurns.setBounds(1070, 133, 222, 17);

        jButton1.setBackground(new java.awt.Color(204, 51, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("See Computer Player Statistics");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(1140, 10, 210, 25);

        lblPAndL1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPAndL1.setText("P & L                    :");
        add(lblPAndL1);
        lblPAndL1.setBounds(42, 176, 121, 17);

        lblAccBal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAccBal1.setText("Account Balance :");
        add(lblAccBal1);
        lblAccBal1.setBounds(40, 130, 123, 17);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FxMediaExample2.frame.openDialog();
        if(jButton1.getText().equals("See my statistics")){
            getTransaction(player);
            jButton1.setText("See Computer Player Statistics");
        }
        else{
            getTransaction(ComputerPlayer.computerPlayer);
            jButton1.setText("See my statistics");
        }
        
        FxMediaExample2.frame.closeDialog();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblAccBal;
    private javax.swing.JLabel lblAccBal1;
    private javax.swing.JLabel lblPAndL;
    private javax.swing.JLabel lblPAndL1;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblRemainingTurns;
    // End of variables declaration//GEN-END:variables

    
    public JPanel addCurrentOrders(int id,String stock, double enterPrice,double lastPrice, int quant,int tag ){
       
            System.out.println("sell :"+jPanel13.getWidth());
            JPanel p= new JPanel();
            p.setLayout(null);
            p.setSize(new Dimension(1243, 48));
            p.setBounds(x, y1, jTabbedPane1.getWidth(), 48);
            //.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            p.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 153)));
            p.setVisible(true);
            if(tag==0){
                p.setBackground(new Color(0,102,102));
            }
            else if(tag==1){
                p.setBackground(Color.black);
            }
            
            int xx=0;
            JLabel lblSymbol = new JLabel();
            lblSymbol.setFont(new Font("Tahoma", 1, 18));
            lblSymbol.setForeground(Color.WHITE);
            lblSymbol.setBounds((int)(p.getWidth()*0.00804505), 15, 180, 22);
            
            
            JLabel lblEprice = new JLabel();
            lblEprice.setFont(new Font("Tahoma", 0, 12));
            lblEprice.setForeground(Color.white);
            lblEprice.setBounds((int)(p.getWidth()*0.1689461), 20, 180, 15);
            
            JLabel lblLprice = new JLabel();
            lblLprice.setFont(new Font("Tahoma", 0, 12));
            lblLprice.setForeground(Color.white);
            lblLprice.setBounds((int)(p.getWidth()*0.32180209), 20, 180, 15);
            
            JLabel lblQuant = new JLabel();
            lblQuant.setFont(new Font("Tahoma", 0, 12));
            lblQuant.setForeground(Color.white);
            lblQuant.setBounds((int)(p.getWidth()*0.47465809), 20, 180, 15);
            
            JLabel lblAmount = new JLabel();
            lblAmount.setFont(new Font("Tahoma", 0, 12));
            lblAmount.setForeground(Color.white);
            lblAmount.setBounds((int)(p.getWidth()*0.62751408), 20, 180, 15);
            
            JLabel lblPL = new JLabel();
            lblPL.setFont(new Font("Tahoma", 1, 12));
            lblPL.setForeground(Color.white);
            lblPL.setBounds((int)(p.getWidth()*0.78037007), 20, 150, 15);
            
            JButton btnSell = new JButton();
            btnSell.setFont(new Font("Tahoma", 0, 12));
            btnSell.setBounds((int)(p.getWidth()*0.90909091), 13, 85,23);
            if(tag==0){
                btnSell.setBackground(Color.black);
                btnSell.setForeground(Color.white);
            }
            else if(tag==1){
                btnSell.setBackground(Color.lightGray);
                btnSell.setForeground(Color.black);
            }
            if(Frame.suspend==1){
                btnSell.setEnabled(false);
            }
            lblSymbol.setText(stock);
            lblEprice.setText("Entry Price : "+enterPrice);
            lblLprice.setText("Last Price : "+lastPrice);
            lblQuant.setText("Quantity : "+quant);
            lblAmount.setText("Amount : "+quant*enterPrice);
            double pl=quant*(lastPrice-enterPrice);
            pl=Math.round(pl*100)/100;
            profitAndLost=profitAndLost+pl;
            lblPL.setText("P&L : "+pl);
            if(pl>0){
                lblPL.setForeground(Color.GREEN);
            }
            else{
                lblPL.setForeground(Color.RED);
            }
            btnSell.setText("Sell Order");
            btnSell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnSell.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    new Timer().schedule(new TimerTask() {
                        @Override
                        public void run() {
                            Clock c= new Clock();
                            c.setDate(Frame.date);
                            sellOrder(stock, quant, lastPrice, id);
                        }
                    }, 0);
                }
            });
            
            Timer t= new Timer();
            t.schedule(new TimerTask() {
                @Override
                public void run() {
                    try {
                        Stock s= YahooFinance.get(stock);
                        double price=s.getQuote().getAsk().setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();
                        double p=quant*(price-enterPrice);
                        p=Math.round(p*100)/100;
                        lblLprice.setText("Last Price : "+price);
                        profitAndLost=(profitAndLost-Double.parseDouble(lblPL.getText().substring(6)))+p;
                        lblPL.setText("P&L : "+p);
                        lblPAndL.setText(""+Math.round(profitAndLost*100)/100);
                        if(profitAndLost>=0){
                            lblPAndL.setForeground(Color.GREEN);
                        }
                        else{
                            lblPAndL.setForeground(Color.red);
                        }
                            if(p>0){
                                lblPL.setForeground(Color.GREEN);
                            }
                            else{
                                lblPL.setForeground(Color.RED);
                            }
                    } catch (IOException ex) {
                        Logger.getLogger(panelPortfolios.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }, 0, 60000);
            
            lblSymbol.setVisible(true);
            lblEprice.setVisible(true);
            lblLprice.setVisible(true);
            lblQuant.setVisible(true);
            lblAmount.setVisible(true);
            lblPL.setVisible(true);
            btnSell.setVisible(true);
            
            p.add(lblSymbol);
            p.add(lblEprice);
            p.add(lblLprice);
            p.add(lblQuant);
            p.add(lblAmount);
            p.add(lblPL);
            p.add(btnSell);
            
        return p;
        
    }
    
    public JPanel addHistory(String stock, double enterPrice, int quant, String type,int y){
       
            
            JPanel p= new JPanel();
            p.setLayout(null);
            p.setSize(new Dimension(1243, 48));
            p.setBounds(x, y, jTabbedPane1.getWidth(), 48);
            //.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            p.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(162, 86, 11)));
            p.setVisible(true);
            p.setBackground(new Color(162,86,11));
            
            JLabel lblSymbol = new JLabel();
            lblSymbol.setFont(new Font("Tahoma", 1, 18));
            lblSymbol.setForeground(Color.WHITE);
            lblSymbol.setBounds((int)(p.getWidth()*0.00804505), 15, 180, 22);
            
            JLabel lblEprice = new JLabel();
            lblEprice.setFont(new Font("Tahoma", 0, 12));
            lblEprice.setForeground(Color.white);
            lblEprice.setBounds((int)(p.getWidth()*0.1689461), 20, 180, 15);
            
            JLabel lblQuant = new JLabel();
            lblQuant.setFont(new Font("Tahoma", 0, 12));
            lblQuant.setForeground(Color.white);
            lblQuant.setBounds((int)(p.getWidth()*0.34593725), 20, 180, 15);
            
            JLabel lblAmount = new JLabel();
            lblAmount.setFont(new Font("Tahoma", 0, 12));
            lblAmount.setForeground(Color.white);
            lblAmount.setBounds((int)(p.getWidth()*0.5229284), 20, 180, 15);
            
            JLabel lblType = new JLabel();
            lblType.setFont(new Font("Tahoma", 0, 12));
            lblType.setForeground(Color.white);
            lblType.setBounds((int)(p.getWidth()*0.69991955), 20, 150, 15);
            
            lblSymbol.setText(stock);
            lblEprice.setText("Price : "+enterPrice);
            lblQuant.setText("Quantity : "+quant);
            lblAmount.setText("Amount : "+(enterPrice*quant));
            lblType.setText("Order Type : "+type);
            
            lblSymbol.setVisible(true);
            lblEprice.setVisible(true);
            lblQuant.setVisible(true);
            lblAmount.setVisible(true);
            lblType.setVisible(true);
            
            
            p.add(lblSymbol);
            p.add(lblEprice);
            p.add(lblQuant);
            p.add(lblAmount);
            p.add(lblType);
            
        return p;
        
    }
     
    public void getTransaction(String playerName){
        if(InternetConnection.getInternetStatus()){
            lblAccBal.setText(""+new Bank().getBalance(playerName));
            lblPlayerName.setText(playerName);
            jPanel3.removeAll();
            jPanel7.removeAll();
            jPanel8.removeAll();
            
            y1=10;
            y2=10;
            y3=10;
            
            JTable[] rs=new JTable[2];
            
            rs=new Broker().portfolio(playerName);
            
            StockQuotes s= new StockQuotes();
            String stock="";
            double enterPrice=0.00;
            double lastPrice=0.00;
            int quant=0;
            String type="";
            
            
            for(int i=0; i<rs[0].getRowCount();i++){
                stock=rs[0].getValueAt(i, 2).toString();
                enterPrice=Double.parseDouble(rs[0].getValueAt(i, 4).toString());
                s.setStock(stock);
                lastPrice=s.getBIDPrice();
                quant=Integer.parseInt(rs[0].getValueAt(i, 3).toString());
                type="BUY";
                
                jPanel7.add(addHistory(stock, enterPrice, quant, type,y2));
                y2=y2+50;
                
                if(rs[0].getValueAt(i, 5).toString().equals("active")){
                    if(show==0){
                        jPanel3.add(addCurrentOrders(Integer.parseInt(rs[0].getValueAt(i, 0).toString()),stock, enterPrice, lastPrice, quant,0));
                    }
                    else{
                        int z=0;
                        for (int j = 0; j < Analyst.sell.getItemCount(); j++) {
                           if(Analyst.sell.getItem(j).equals(rs[0].getValueAt(i, 0).toString())){
                                z=1;
                                break;
                            }
                        }
                        if(z==1){
                           jPanel3.add(addCurrentOrders(Integer.parseInt(rs[0].getValueAt(i, 0).toString()),stock, enterPrice, lastPrice, quant,1));
                            
                        }
                        else{
                            jPanel3.add(addCurrentOrders(Integer.parseInt(rs[0].getValueAt(i, 0).toString()),stock, enterPrice, lastPrice, quant,0));
                    
                        }
                    }
                        y1=y1+50;
                }
            }
            
            for(int j=0; j<rs[1].getRowCount();j++){
                stock=rs[1].getValueAt(j, 2).toString();
                enterPrice=Double.parseDouble(rs[1].getValueAt(j, 4).toString());
                quant=Integer.parseInt(rs[1].getValueAt(j, 3).toString());
                type="SELL";
                
                jPanel8.add(addHistory(stock, enterPrice, quant, type,y3));
                y3=y3+50;
            }
            
            jPanel7.setPreferredSize(new Dimension(750, y2+5));
            jPanel8.setPreferredSize(new Dimension(750, y3+5));
            jPanel3.setPreferredSize(new Dimension(750, y1+5));
            
            jScrollPane1.repaint();
            jScrollPane4.repaint();
            jScrollPane2.repaint();
            jPanel1.validate();
            jPanel1.repaint();
            jPanel2.validate();
            jPanel2.repaint();
            lblPAndL.setText(""+Math.round(profitAndLost*100)/100);
            if(profitAndLost>=0){
                lblPAndL.setForeground(Color.GREEN);
            }
            else{
                lblPAndL.setForeground(Color.red);
            }
        }
    }
    
    private void sellOrder(String stock,int quantity, double price,int id){
     
       if(JOptionPane.showConfirmDialog(this,"Do you want to sell this stocks ?","Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION){
            if(InternetConnection.getInternetStatus()){
            openDialog();
            Broker b= new Broker();
            b.sell(player,stock, quantity, price);
            b.update(id);
            double balance=new Bank().getBalance(panelPortfolios.player);
            Frame.balance=balance;
            lblAccBal.setText(""+balance);
            getTransaction(panelPortfolios.player);
            closeDialog();
            }
       }
    }
    
    
    private void openDialog(){
            jDialog1.setUndecorated(true);
            jDialog1.setSize(392, 151);
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            jDialog1.setLocation(dim.width/2-jDialog1.getSize().width/2, dim.height/2-jDialog1.getSize().height/2);
            FxMediaExample2.frame.setEnabled(false);
            jDialog1.setVisible(true);
    }
    
    private void closeDialog(){
            FxMediaExample2.frame.setEnabled(true);
            jDialog1.dispose();
    }
    
}
