/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team.bitcode.stock_market;

import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author SHASHILA
 */
public class panelLeaderBoard extends javax.swing.JPanel {
    int x=0;
    int y=0 ;
    public static JPanel panel;
    /**
     * Creates new form panelLeaderBoard
     */
    public panelLeaderBoard() {
        initComponents();
        panel=jPanel2;
        
        new Timer().schedule(new TimerTask() {
            @Override
            public void run() {
                FxMediaExample2.frame.openDialog();
                if(InternetConnection.getInternetStatus()){
                    showLeaderBoard();
                }
                
                FxMediaExample2.frame.closeDialog();
            }
        }, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog2 = new javax.swing.JDialog();
        jPanel12 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        lblStockName = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        buyTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        SellTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();

        jDialog2.setAlwaysOnTop(true);
        jDialog2.setBackground(new java.awt.Color(204, 0, 0));
        jDialog2.setUndecorated(true);
        jDialog2.setResizable(false);

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblStockName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStockName.setForeground(new java.awt.Color(255, 255, 255));
        lblStockName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStockName.setText("Transaction History");

        jPanel4.setLayout(new java.awt.BorderLayout());

        buyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock", "Quantity", "Price", "Amount"
            }
        ));
        jScrollPane3.setViewportView(buyTable);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Buy Order History", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        SellTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock", "Quantity", "Price", "Amount"
            }
        ));
        jScrollPane4.setViewportView(SellTable);

        jPanel5.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Sell Order History", jPanel5);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblStockName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblStockName)
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SCORE BOARD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(73, 19, 131, 22);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 869, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel3);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(230, 70, 871, 430);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        closeTableData();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SellTable;
    private javax.swing.JTable buyTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblStockName;
    // End of variables declaration//GEN-END:variables


     public JPanel setTab(String name, double bal){
       JPanel p= new JPanel();
            p.setLayout(null);
            p.setSize(new Dimension(1190, 80));
            p.setBounds(x, y, jPanel1.getWidth(), 80);
            p.setBackground(Color.black);
            p.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 153)));
            p.setVisible(true);
            
            JLabel lblName = new JLabel();
            lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); 
            lblName.setForeground(new java.awt.Color(255, 255, 255));
            lblName.setBounds((int)(p.getWidth()*0.01377727), 10, 250, 30);
            lblName.setText("Player Name: :"+name);
            
            JLabel lblBal = new JLabel();
            lblBal.setFont(new java.awt.Font("Tahoma", 1, 14)); 
            lblBal.setForeground(new java.awt.Color(255, 255, 255));
            lblBal.setBounds((int)(p.getWidth()*0.32950631), 10, 250, 30);
            lblBal.setText("Account Balance: "+bal);
            
            JButton btnClick = new JButton();
            btnClick.setBackground(Color.green);
            btnClick.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            btnClick.setForeground(Color.WHITE);
            btnClick.setText("Show History");
            btnClick.setBounds((int)(p.getWidth()*0.61653272), 10, 200, 23);
            
            btnClick.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    
                        showHistory(name);
                }
            });
           
            p.add(lblName);
            p.add(lblBal);
            p.add(btnClick);
            
        return p;
            
           
            
            
    }
     
     public void showLeaderBoard(){
        try {
          
             
            jPanel3.removeAll();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://65.19.141.67:3306/piyumald_stock","piyumald_piyumal","c19940603c");
            Statement stmnt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet rs= stmnt.executeQuery("select * from Bank ORDER BY balance DESC");
            y=0;
            while(rs.next()){
               jPanel3.add(setTab(rs.getString(1), rs.getDouble(2)));
               y=y+85;
            }
                    jPanel3.setPreferredSize(new Dimension(1190, y+5));
                    jScrollPane1.repaint();
                    jPanel2.validate();
                    jPanel2.repaint();
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(panelLeaderBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(panelLeaderBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
     
     public void showHistory(String name){
        try {
            
             
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment( JLabel.CENTER );
            buyTable.setDefaultRenderer(String.class, centerRenderer);
            SellTable.setDefaultRenderer(String.class, centerRenderer);
            
            
            Object[] buy= new Object[4];
            Object[] sell= new Object[4];
            DefaultTableModel modelBuy =(DefaultTableModel)buyTable.getModel();
            DefaultTableModel modelSell =(DefaultTableModel)SellTable.getModel();
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://65.19.141.67:3306/piyumald_stock","piyumald_piyumal","c19940603c");
            Statement stmnt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet rs= stmnt.executeQuery("select * from Buy where name=(select broker_name from Broker where player_name = '"+name+"')");
            while(rs.next()){
                buy[0]=rs.getString(3);
                buy[1]=rs.getInt(4);
                buy[2]=rs.getDouble(5);
                buy[3]=rs.getInt(4)*rs.getDouble(5);
                modelBuy.addRow(buy);
            }
            
            ResultSet rs1= stmnt.executeQuery("select * from Sell where name=(select broker_name from Broker where player_name = '"+name+"')");
            while(rs1.next()){
                sell[0]=rs1.getString(3);
                sell[1]=rs1.getInt(4);
                sell[2]=rs1.getDouble(5);
                sell[3]=rs1.getInt(4)*rs.getDouble(5);
                modelSell.addRow(sell);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(panelLeaderBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(panelLeaderBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                
     }
     public void openTableData(){
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            jDialog2.setUndecorated(true);
            jDialog2.setSize(927, 459);
            jDialog2.setLocation(dim.width/2-jDialog2.getSize().width/2, dim.height/2-jDialog2.getSize().height/2);
            jDialog2.setVisible(true);
            FxMediaExample2.frame.setEnabled(false);
            
    }
    
    public void closeTableData(){
            FxMediaExample2.frame.setEnabled(true);
            jDialog2.dispose();
    }
    
    /*private static class JTableButtonRenderer implements TableCellRenderer {
    @Override public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
    JButton button = (JButton)value;
    return button;
    }
    
    
    }*/
    
}