/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team.bitcode.stock_market;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.DriverManager.*;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author DUSH
 */
public class panelPlayer extends javax.swing.JPanel {
    public int code=0;
    public static JLabel lblImage;
    public static JPanel panel;
    
    /**
     * Creates new form panelPlayer
     */
    public panelPlayer() {
        initComponents();
        panel=jPanel1;
        lblImage=jLabel2;
        
        panelSignup.setVisible(false);
        jPanel2.setVisible(false);
        panelReset.setVisible(false);
        panelResetPass.setVisible(false);
        panelLogin.setVisible(true);
        jPanel1.removeAll();
        
        jPanel1.add(panelLogin);
        
        btnBack.setVisible(false);
       
        this.repaint();
        this.revalidate();
        lblDescription.setVisible(false);
        txtVerify.setVisible(false);
        btnVeriy.setVisible(false);
        FxMediaExample2.frame.setEnabled(true);
        this.setSize(FxMediaExample2.frame.getWidth(), (int)(FxMediaExample2.frame.getHeight()*0.861979167));
        this.repaint();
        this.revalidate();
        //this.setBounds(0, (int)(FxMediaExample2.frame.getHeight()*0.1171875), FxMediaExample2.frame.getWidth(), (int)(FxMediaExample2.frame.getHeight()*0.861979167));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnForgetPass = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        panelReset = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNewEmail = new javax.swing.JTextField();
        txtVerify = new javax.swing.JTextField();
        btnVeriy = new javax.swing.JButton();
        lblDescription = new javax.swing.JLabel();
        panelResetPass = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        txtResetPass = new javax.swing.JPasswordField();
        txtResetPass2 = new javax.swing.JPasswordField();
        btnSendCode = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelSignup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNewPlayerName = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        lblPlayerExist = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtContinuePass = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        panelLogin.setBackground(new java.awt.Color(0, 20, 21));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Enter Player Name");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Password");

        txtPlayerName.setBackground(new java.awt.Color(204, 204, 204));
        txtPlayerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPlayerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPlayerNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlayerNameKeyReleased(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(0, 102, 153));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnForgetPass.setBackground(new java.awt.Color(0, 102, 153));
        btnForgetPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnForgetPass.setForeground(new java.awt.Color(255, 255, 255));
        btnForgetPass.setText("Forget Password");
        btnForgetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgetPassActionPerformed(evt);
            }
        });

        btnSignup.setBackground(new java.awt.Color(0, 102, 153));
        btnSignup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Signup");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        txtPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelLoginLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLoginLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnForgetPass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnForgetPass)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnSignup))
                .addContainerGap(314, Short.MAX_VALUE))
        );

        panelReset.setBackground(new java.awt.Color(0, 20, 21));

        jLabel8.setBackground(new java.awt.Color(0, 102, 153));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Enter E-mail");

        txtNewEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtNewEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNewEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewEmailKeyReleased(evt);
            }
        });

        txtVerify.setBackground(new java.awt.Color(204, 204, 204));
        txtVerify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerifyActionPerformed(evt);
            }
        });
        txtVerify.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVerifyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVerifyKeyReleased(evt);
            }
        });

        btnVeriy.setBackground(new java.awt.Color(0, 102, 153));
        btnVeriy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVeriy.setForeground(new java.awt.Color(255, 255, 255));
        btnVeriy.setText("Verify");
        btnVeriy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeriyActionPerformed(evt);
            }
        });

        lblDescription.setForeground(new java.awt.Color(0, 204, 255));
        lblDescription.setText("Please enter reset code to send your email");

        panelResetPass.setBackground(new java.awt.Color(0, 20, 21));

        jLabel10.setBackground(new java.awt.Color(0, 102, 153));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");

        jLabel11.setBackground(new java.awt.Color(0, 102, 153));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Confirm Password");

        btnReset.setBackground(new java.awt.Color(0, 102, 153));
        btnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtResetPass.setBackground(new java.awt.Color(204, 204, 204));
        txtResetPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtResetPass2.setBackground(new java.awt.Color(204, 204, 204));
        txtResetPass2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelResetPassLayout = new javax.swing.GroupLayout(panelResetPass);
        panelResetPass.setLayout(panelResetPassLayout);
        panelResetPassLayout.setHorizontalGroup(
            panelResetPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResetPassLayout.createSequentialGroup()
                .addGroup(panelResetPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReset)
                    .addGroup(panelResetPassLayout.createSequentialGroup()
                        .addGroup(panelResetPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(panelResetPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtResetPass, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtResetPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panelResetPassLayout.setVerticalGroup(
            panelResetPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResetPassLayout.createSequentialGroup()
                .addGroup(panelResetPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtResetPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelResetPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtResetPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnReset)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        btnSendCode.setBackground(new java.awt.Color(0, 102, 153));
        btnSendCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSendCode.setForeground(new java.awt.Color(255, 255, 255));
        btnSendCode.setText("Send Code");
        btnSendCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelResetLayout = new javax.swing.GroupLayout(panelReset);
        panelReset.setLayout(panelResetLayout);
        panelResetLayout.setHorizontalGroup(
            panelResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResetLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(panelResetPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResetLayout.createSequentialGroup()
                .addGroup(panelResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelResetLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVeriy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelResetLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelResetLayout.createSequentialGroup()
                                .addComponent(lblDescription)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelResetLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(56, 56, 56)
                                .addComponent(txtNewEmail))))
                    .addGroup(panelResetLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSendCode)
                .addGap(51, 51, 51))
        );
        panelResetLayout.setVerticalGroup(
            panelResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResetLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendCode))
                .addGap(18, 18, 18)
                .addComponent(lblDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtVerify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnVeriy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(panelResetPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        setBackground(new java.awt.Color(0, 20, 21));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.BorderLayout());

        panelSignup.setBackground(new java.awt.Color(0, 20, 21));

        jLabel1.setBackground(new java.awt.Color(0, 102, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Player Name");

        txtNewPlayerName.setBackground(new java.awt.Color(204, 204, 204));
        txtNewPlayerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNewPlayerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewPlayerNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewPlayerNameKeyReleased(evt);
            }
        });

        btnCheck.setBackground(new java.awt.Color(0, 102, 153));
        btnCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCheck.setForeground(new java.awt.Color(255, 255, 255));
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        lblPlayerExist.setBackground(new java.awt.Color(0, 102, 153));
        lblPlayerExist.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlayerExist.setForeground(new java.awt.Color(255, 0, 0));
        lblPlayerExist.setText(" ");

        jPanel2.setBackground(new java.awt.Color(0, 20, 21));

        jLabel5.setBackground(new java.awt.Color(0, 102, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-mail");

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 102, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        btnContinue.setBackground(new java.awt.Color(0, 102, 153));
        btnContinue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnContinue.setForeground(new java.awt.Color(255, 255, 255));
        btnContinue.setText("Continue");
        btnContinue.setEnabled(false);
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 102, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm Password");

        txtPass.setBackground(new java.awt.Color(204, 204, 204));
        txtPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtContinuePass.setBackground(new java.awt.Color(204, 204, 204));
        txtContinuePass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnContinue))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContinuePass, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(91, 91, 91))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContinuePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btnContinue)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnBack.setBackground(new java.awt.Color(0, 102, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSignupLayout = new javax.swing.GroupLayout(panelSignup);
        panelSignup.setLayout(panelSignupLayout);
        panelSignupLayout.setHorizontalGroup(
            panelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignupLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSignupLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNewPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack))
                    .addComponent(lblPlayerExist, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSignupLayout.setVerticalGroup(
            panelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignupLayout.createSequentialGroup()
                .addGroup(panelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSignupLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(panelSignupLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNewPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCheck)
                            .addComponent(btnBack))))
                .addGap(6, 6, 6)
                .addComponent(lblPlayerExist)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelSignup, java.awt.BorderLayout.CENTER);

        add(jPanel1);
        jPanel1.setBounds(400, 120, 553, 482);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(600, 20, 100, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewPlayerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPlayerNameKeyPressed

    }//GEN-LAST:event_txtNewPlayerNameKeyPressed

    private void txtNewPlayerNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPlayerNameKeyReleased
          if(btnContinue.isEnabled()){
              btnContinue.setEnabled(false);
              jPanel2.setVisible(false);
          }
    }//GEN-LAST:event_txtNewPlayerNameKeyReleased

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        
        if(notEmpty(txtNewPlayerName.getText())){
        
            if(checkPlayerExist()){
                lblPlayerExist.setText("Entered player already exist. Try different one.");
                btnContinue.setEnabled(false);
                jPanel2.setVisible(false);
            }
            else{
                lblPlayerExist.setText("");
                btnContinue.setEnabled(true);
                jPanel2.setVisible(true);
            }
        }    
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        if(InternetConnection.getInternetStatus()){
        if(new SendEmail().verifyEmail(txtEmail.getText(),0)){
            if(checkPass(txtPass, txtContinuePass)){
                new Timer().schedule(new TimerTask() {
                    @Override
                    public void run() {
                        FxMediaExample2.frame.openDialog();
                        if(insertPlayer(txtNewPlayerName.getText())==false){
                            JOptionPane.showMessageDialog(null, "Player already exist. Try differnt name.", "Payer Exist", JOptionPane.WARNING_MESSAGE);
                        }
                        else{
                        if(Frame.log==1){
                            insertComputerPlayer();
                        }
                    
                        btnBack.setVisible(false);
                        panelSignup.setVisible(false);
                        panelLogin.setVisible(true);
                        panelLogin.setBounds(0, 0, 553, 482);
                        panelSignup.getParent().add(panelLogin);
                        panelSignup.getParent().repaint();
                        panelSignup.getParent().revalidate();
                }
              FxMediaExample2.frame.closeDialog();          
            }
        }, 0);
            }
            else{
                JOptionPane.showMessageDialog(FxMediaExample2.frame, "Password not matched. Try again", "Password", JOptionPane.WARNING_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(FxMediaExample2.frame, "Please enter valid email.", "Invalid Email", JOptionPane.WARNING_MESSAGE);
       }

        }
        
        
    }//GEN-LAST:event_btnContinueActionPerformed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyReleased

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            File f = new File("players/player_name.plyr");
            BufferedReader b = new BufferedReader(new FileReader(f));
            String readLine = "";
            
            while ((readLine = b.readLine()) != null) {
                if(readLine.equals(txtPlayerName.getText())){
                    if(InternetConnection.getInternetStatus()){
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://65.19.141.67:3306/piyumald_stock","piyumald_piyumal","c19940603c");
                    Statement stmnt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    ResultSet rs=stmnt.executeQuery("select * from Bank where player_name='"+txtPlayerName.getText()+"'");
                    rs.next();
                    char[] pass=txtPassword.getPassword();
                    String password="";
                    for(int i=0; i< pass.length;i++){
                        password=password+pass[i];
                    }
                    if(password.equals(rs.getString(4))){
                        
                        new Timer().schedule(new TimerTask() {
                            @Override
                            public void run() {
                                try {
                                    FxMediaExample2.frame.openDialog();
                                    ComputerPlayer c=new ComputerPlayer();
                                    c.setComputerPlayerNameFromFile();
                                    c.setDate();
                                    c.setBalance();
                                    Clock cl= new Clock();
                                    cl.setDate(ComputerPlayer.date);
                                    ComputerPlayer.myturn=1441-cl.now();
                                    c.play();
                                    panelPortfolios.player=txtPlayerName.getText();
                                    Frame.log=0;
                                    Frame.balance=new Bank().getBalance(txtPlayerName.getText());
                                    Frame.suspend=0;
                                    FxMediaExample2.frame.lblRemain.setVisible(false);
                                    FxMediaExample2.frame.activePlayer();
                                    SelectPlayer.setPlayerDate(txtPlayerName.getText());
                                    Frame.showRemaningTurns();
                                    if(Frame.timerRecommendation!=null){
                                        Frame.timerRecommendation.cancel();
                                    }
                                    FxMediaExample2.frame.startRecommendation();
                                    Frame.showTradingCenter();
                                    FxMediaExample2.frame.closeDialog();
                                } catch (IOException ex) {
                                    Logger.getLogger(panelPlayer.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }, 0);
                       
                    }
                    else{
                        JOptionPane.showMessageDialog(FxMediaExample2.frame, "Incorrect Password. Try again.", "Incorrect Password", JOptionPane.WARNING_MESSAGE);
                    }
                    
                    break;
                }
                }
                else{
                    JOptionPane.showMessageDialog(FxMediaExample2.frame, "Player not available.", "Not found", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(panelPlayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(panelPlayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(panelPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnForgetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgetPassActionPerformed
        panelLogin.setVisible(false);
        btnBack.setVisible(true);
        jPanel1.removeAll();
        panelReset.setVisible(true);
        panelReset.setBounds(0, 0, 553, 482);
        jPanel1.add(panelReset);
        btnSendCode.setEnabled(true);
        txtNewEmail.setEnabled(true);
        lblDescription.setVisible(false);
        txtVerify.setVisible(false);
        btnVeriy.setVisible(false);
        panelResetPass.setVisible(false);
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_btnForgetPassActionPerformed

    private void txtNewEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewEmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewEmailKeyPressed

    private void txtNewEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewEmailKeyReleased

    private void txtVerifyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVerifyKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVerifyKeyPressed

    private void txtVerifyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVerifyKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVerifyKeyReleased

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        if(checkPass(txtResetPass, txtResetPass2)){
            if(InternetConnection.getInternetStatus()){
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://65.19.141.67:3306/piyumald_stock","piyumald_piyumal","c19940603c");
                    Statement stmnt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                     String password="";
                     char[] pass=txtResetPass.getPassword();
                        for(int i=0; i< pass.length;i++){
                            password=password+pass[i];
                        }
                    stmnt.execute("Update Bank set password='"+password+"' where email='"+txtNewEmail.getText()+"'");
                    panelResetPass.setVisible(false);
                    panelReset.setVisible(false);
                    panelLogin.setVisible(true);
                    panelLogin.setBounds(0, 0, 553, 482);
                    this.add(panelLogin);
                    this.repaint();
                    this.revalidate();
                    txtNewEmail.setText("");
                    txtResetPass.setText("");
                    txtResetPass2.setText("");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(panelPlayer.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(panelPlayer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(FxMediaExample2.frame, "Password not matched. Try again", "Reset Password", JOptionPane.WARNING_MESSAGE);
        }
          
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnVeriyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeriyActionPerformed
        if(txtVerify.getText().equals(code+"")){
            txtVerify.setEnabled(false);
            btnVeriy.setEnabled(false);
            panelResetPass.setVisible(true);
            
        }
        else{
            JOptionPane.showMessageDialog(FxMediaExample2.frame, "Wrong verification code", "Verification", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnVeriyActionPerformed

    private void txtVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVerifyActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        panelLogin.setVisible(false);
        jPanel1.removeAll();
        panelSignup.setVisible(true);
        jPanel1.add(panelSignup);
        btnBack.setVisible(true);
    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnSendCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendCodeActionPerformed
       if(InternetConnection.getInternetStatus()){
           new SendEmail().setAuthernication();
        if(new SendEmail().verifyEmail(txtNewEmail.getText(),1)){
           SendEmail em= new SendEmail();
           code=em.sendVerifyCode(txtNewEmail.getText());
           txtNewEmail.setEnabled(false);
           btnSendCode.setEnabled(false);
           lblDescription.setVisible(true);
           btnVeriy.setEnabled(true);
           btnVeriy.setVisible(true);
           txtVerify.setEnabled(true);
           txtVerify.setVisible(true);
           
       }
       else{
           JOptionPane.showMessageDialog(FxMediaExample2.frame, "Please enter valid email.", "Invalid Email", JOptionPane.WARNING_MESSAGE);
       }
       }
    }//GEN-LAST:event_btnSendCodeActionPerformed

    private void txtPlayerNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlayerNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlayerNameKeyReleased

    private void txtPlayerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlayerNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlayerNameKeyPressed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       panelSignup.setVisible(false);
       panelLogin.setVisible(true);
       jPanel1.removeAll();
       jPanel1.add(panelLogin);
       btnBack.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnForgetPass;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSendCode;
    private javax.swing.JButton btnSignup;
    private javax.swing.JButton btnVeriy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblPlayerExist;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelReset;
    private javax.swing.JPanel panelResetPass;
    private javax.swing.JPanel panelSignup;
    private javax.swing.JPasswordField txtContinuePass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNewEmail;
    private javax.swing.JTextField txtNewPlayerName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPlayerName;
    private javax.swing.JPasswordField txtResetPass;
    private javax.swing.JPasswordField txtResetPass2;
    private javax.swing.JTextField txtVerify;
    // End of variables declaration//GEN-END:variables

    private boolean checkPlayerExist() {
        boolean flag=false;
        try {
            if(InternetConnection.getInternetStatus()){
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://65.19.141.67:3306/piyumald_stock","piyumald_piyumal","c19940603c");
            Statement stmnt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet rs=stmnt.executeQuery("select * from Bank");
            while(rs.next()){
                if(txtNewPlayerName.getText().equals(rs.getString(1))){
                   flag=true;
                   break;
                }
            }
            con.close();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(panelPlayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(panelPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    return flag;
    }

    private boolean insertPlayer(String name) {
        boolean flag=false;
        try {
            char[] pass=txtPass.getPassword();
            String password="";
            for(int i=0; i< pass.length;i++){
                password=password+pass[i];
            }
            Bank b= new Bank();
            Clock c= new Clock();
            c.setDate(new Date());
            flag=b.createAccount(new Clock().now(), name,txtEmail.getText(),password);
            Player p= new Player();
            p.createFile(name,"players/player_name.plyr");
            panelPortfolios.player=name;
            
        } catch (IOException ex) {
            Logger.getLogger(panelPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
        return flag;
    }
    private void insertComputerPlayer() {
        try {
            new ComputerPlayer().setComputerPlayerName();
            Bank b= new Bank();
            Clock c= new Clock();
            c.setDate(new Date());
            b.createAccount(new Clock().now(), ComputerPlayer.computerPlayer,"","");
            Player p= new Player();
            p.createFile(ComputerPlayer.computerPlayer,"players/computer_player_name.plyr");
        } catch (IOException ex) {
            Logger.getLogger(panelPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public boolean notEmpty(String s){
        boolean flag=false;
		if(s != null && !s.isEmpty() && !s.trim().isEmpty()){
		
			flag=true;
		}
		else{
			flag=false;
		}
            return flag;
    }
    
    boolean checkPass(JPasswordField pass1, JPasswordField pass2){
        boolean flag=false;
        if(pass1.getPassword().length!=0 && pass2.getPassword().length!=0){
            char[] psw1 = pass1.getPassword();
            char[] psw2 = pass2.getPassword();
            if(Arrays.equals(psw1, psw2)){
                flag= true;
                System.err.println("Match");
            }
        }
        return flag;
    }
    
    public void signupFromAfterLogin(){
        panelLogin.setVisible(false);
        jPanel1.removeAll();
        panelSignup.setVisible(true);
        jPanel1.add(panelSignup);
        
        btnBack.setVisible(false);
    }

}
