/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team.bitcode.stock_market;

import java.awt.Dimension;
import java.awt.List;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author DUSH
 */
public class panelBuyRecomendation extends javax.swing.JPanel {
    
    /**
     * Creates new form panelBuyRecomendation
     */
    public panelBuyRecomendation() {
        initComponents();
        new Timer().schedule(new TimerTask() {
            @Override
            public void run() {
                FxMediaExample2.frame.openDialog();
                panelContainer.removeAll();
                FxMediaExample2.frame.y=10;
                for(int i=0;i<Analyst.buy.getItemCount();i++){
                    if(InternetConnection.getInternetStatus()){
                        panelContainer.add(FxMediaExample2.frame.setTab(Analyst.buy.getItem(i), Analyst.buyListSector.getItem(i)));
                        FxMediaExample2.frame.y=FxMediaExample2.frame.y+75;
                    }
                    else{
                        break;
                    }
                }
                panelContainer.setPreferredSize(new Dimension(740, FxMediaExample2.frame.y+20));
                jScrollPane1.repaint();
                panel.validate();
                panel.repaint();
                FxMediaExample2.frame.closeDialog();
            }
        }, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelContainer = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        panelContainer.setBackground(new java.awt.Color(255, 255, 255));
        panelContainer.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout panelContainerLayout = new javax.swing.GroupLayout(panelContainer);
        panelContainer.setLayout(panelContainerLayout);
        panelContainerLayout.setHorizontalGroup(
            panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        panelContainerLayout.setVerticalGroup(
            panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelContainer);

        panel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(panel);
        panel.setBounds(0, 0, 760, 430);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(653, 440, 100, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Frame.jtab.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelContainer;
    // End of variables declaration//GEN-END:variables

    public void setBuyReomendation(String stock, String sector) {
        
        
    }
}
